name: Generate snake game

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update data
    runs-on: ubuntu-latest
    steps:
      # Check out the repository to the GitHub Actions runner
      - name: Checkout repository
        uses: actions/checkout@v2

      # Snake Animation
      - name: Generate snake animation
        uses: Platane/snk@v2.0.0
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contribution-grid-snake.svg
          color_snake: red # Use the correct parameter for color if supported

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
